class EventStatus:
    """Event status constants for agent lifecycle events"""

    # Session lifecycle
    SESSION_INITIATED = "SESSION_INITIATED"

    # Lambda invoker → AgentCore communication
    AGENT_INVOCATION_STARTED = "AGENT_INVOCATION_STARTED"
    AGENT_INVOCATION_SUCCEEDED = "AGENT_INVOCATION_SUCCEEDED"
    AGENT_INVOCATION_FAILED = "AGENT_INVOCATION_FAILED"

    # Agent invoke and background task
    AGENT_RUNTIME_INVOKE_STARTED = "AGENT_RUNTIME_INVOKE_STARTED"
    AGENT_RUNTIME_INVOKE_FAILED = "AGENT_RUNTIME_INVOKE_FAILED"
    AGENT_BACKGROUND_TASK_STARTED = "AGENT_BACKGROUND_TASK_STARTED"
    AGENT_BACKGROUND_TASK_COMPLETED = "AGENT_BACKGROUND_TASK_COMPLETED"
    AGENT_BACKGROUND_TASK_FAILED = "AGENT_BACKGROUND_TASK_FAILED"

    # Task/Phase tracking - Discovery phase
    TASK_DISCOVERY_STARTED = "TASK_DISCOVERY_STARTED"
    TASK_DISCOVERY_COMPLETED = "TASK_DISCOVERY_COMPLETED"
    TASK_DISCOVERY_FAILED = "TASK_DISCOVERY_FAILED"

    # Task/Phase tracking - Usage and Metrics Collection phase
    TASK_USAGE_AND_METRICS_COLLECTION_STARTED = "TASK_USAGE_AND_METRICS_COLLECTION_STARTED"
    TASK_USAGE_AND_METRICS_COLLECTION_COMPLETED = "TASK_USAGE_AND_METRICS_COLLECTION_COMPLETED"
    TASK_USAGE_AND_METRICS_COLLECTION_FAILED = "TASK_USAGE_AND_METRICS_COLLECTION_FAILED"

    # Task/Phase tracking - Analysis and Decision Rules phase
    TASK_ANALYSIS_AND_DECISION_RULES_STARTED = "TASK_ANALYSIS_AND_DECISION_RULES_STARTED"
    TASK_ANALYSIS_AND_DECISION_RULES_COMPLETED = "TASK_ANALYSIS_AND_DECISION_RULES_COMPLETED"
    TASK_ANALYSIS_AND_DECISION_RULES_FAILED = "TASK_ANALYSIS_AND_DECISION_RULES_FAILED"

    # Task/Phase tracking - Recommendation Format phase
    TASK_RECOMMENDATION_FORMAT_STARTED = "TASK_RECOMMENDATION_FORMAT_STARTED"
    TASK_RECOMMENDATION_FORMAT_COMPLETED = "TASK_RECOMMENDATION_FORMAT_COMPLETED"
    TASK_RECOMMENDATION_FORMAT_FAILED = "TASK_RECOMMENDATION_FORMAT_FAILED"

    # Task/Phase tracking - Cost Estimation Method phase
    TASK_COST_ESTIMATION_METHOD_STARTED = "TASK_COST_ESTIMATION_METHOD_STARTED"
    TASK_COST_ESTIMATION_METHOD_COMPLETED = "TASK_COST_ESTIMATION_METHOD_COMPLETED"
    TASK_COST_ESTIMATION_METHOD_FAILED = "TASK_COST_ESTIMATION_METHOD_FAILED"

    # Task/Phase tracking - Output Contract phase
    TASK_OUTPUT_CONTRACT_STARTED = "TASK_OUTPUT_CONTRACT_STARTED"
    TASK_OUTPUT_CONTRACT_COMPLETED = "TASK_OUTPUT_CONTRACT_COMPLETED"
    TASK_OUTPUT_CONTRACT_FAILED = "TASK_OUTPUT_CONTRACT_FAILED"

    # Task/Phase tracking - S3 Write Requirements phase
    TASK_S3_WRITE_REQUIREMENTS_STARTED = "TASK_S3_WRITE_REQUIREMENTS_STARTED"
    TASK_S3_WRITE_REQUIREMENTS_COMPLETED = "TASK_S3_WRITE_REQUIREMENTS_COMPLETED"
    TASK_S3_WRITE_REQUIREMENTS_FAILED = "TASK_S3_WRITE_REQUIREMENTS_FAILED"
