class EventStatus:
    """Event status constants for agent lifecycle events"""

    # Session lifecycle
    SESSION_INITIATED = "SESSION_INITIATED"

    # Lambda invoker → AgentCore communication
    AGENT_INVOCATION_STARTED = "AGENT_INVOCATION_STARTED"
    AGENT_INVOCATION_SUCCEEDED = "AGENT_INVOCATION_SUCCEEDED"
    AGENT_INVOCATION_FAILED = "AGENT_INVOCATION_FAILED"

    # Agent invoke and background task
    AGENT_RUNTIME_INVOKE_STARTED = "AGENT_RUNTIME_INVOKE_STARTED"
    AGENT_RUNTIME_INVOKE_FAILED = "AGENT_RUNTIME_INVOKE_FAILED"
    AGENT_BACKGROUND_TASK_STARTED = "AGENT_BACKGROUND_TASK_STARTED"
    AGENT_BACKGROUND_TASK_COMPLETED = "AGENT_BACKGROUND_TASK_COMPLETED"
    AGENT_BACKGROUND_TASK_FAILED = "AGENT_BACKGROUND_TASK_FAILED"

    # Task/Phase tracking
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"
    TASK_CANCELLED = "TASK_CANCELLED"
    TASK_SKIPPED = "TASK_SKIPPED"
